version: "3.9"

services:
  ai-service:
    build: ./ai-service
    ports:
      - "8001:8001"
    env_file:
      - ./ai-service/.env
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: farhan2k1
      POSTGRES_DB: adflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: